async function main() {
  // Read the validated output content from environment variable
  const outputContent = process.env.GITHUB_AW_AGENT_OUTPUT;
  if (!outputContent) {
    console.log("No GITHUB_AW_AGENT_OUTPUT environment variable found");
    return;
  }
  if (outputContent.trim() === "") {
    console.log("Agent output content is empty");
    return;
  }

  console.log("Agent output content length:", outputContent.length);

  // Parse the validated output JSON
  let validatedOutput;
  try {
    validatedOutput = JSON.parse(outputContent);
  } catch (error) {
    console.log(
      "Error parsing agent output JSON:",
      error instanceof Error ? error.message : String(error)
    );
    return;
  }

  if (!validatedOutput.items || !Array.isArray(validatedOutput.items)) {
    console.log("No valid items found in agent output");
    return;
  }

  // Find all create-discussion items
  const createDiscussionItems = validatedOutput.items.filter(
    /** @param {any} item */ item => item.type === "create-discussion"
  );
  if (createDiscussionItems.length === 0) {
    console.log("No create-discussion items found in agent output");
    return;
  }

  console.log(
    `Found ${createDiscussionItems.length} create-discussion item(s)`
  );

  // Get discussion categories using REST API
  let discussionCategories = [];
  try {
    const { data: categories } = await github.request(
      "GET /repos/{owner}/{repo}/discussions/categories",
      {
        owner: context.repo.owner,
        repo: context.repo.repo,
      }
    );
    discussionCategories = categories || [];
    console.log(
      "Available categories:",
      discussionCategories.map(cat => ({ name: cat.name, id: cat.id }))
    );
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : String(error);

    // Special handling for repositories without discussions enabled
    if (errorMessage.includes("Not Found") && error.status === 404) {
      console.log(
        "⚠ Cannot create discussions: Discussions are not enabled for this repository"
      );
      console.log(
        "Consider enabling discussions in repository settings if you want to create discussions automatically"
      );
      return; // Exit gracefully without creating discussions
    }

    console.error("Failed to get discussion categories:", errorMessage);
    throw error;
  }

  // Determine category ID
  let categoryId = process.env.GITHUB_AW_DISCUSSION_CATEGORY_ID;
  if (!categoryId && discussionCategories.length > 0) {
    // Default to the first category if none specified
    categoryId = discussionCategories[0].id;
    console.log(
      `No category-id specified, using default category: ${discussionCategories[0].name} (${categoryId})`
    );
  }
  if (!categoryId) {
    console.error(
      "No discussion category available and none specified in configuration"
    );
    throw new Error("Discussion category is required but not available");
  }

  const createdDiscussions = [];

  // Process each create-discussion item
  for (let i = 0; i < createDiscussionItems.length; i++) {
    const createDiscussionItem = createDiscussionItems[i];
    console.log(
      `Processing create-discussion item ${i + 1}/${createDiscussionItems.length}:`,
      {
        title: createDiscussionItem.title,
        bodyLength: createDiscussionItem.body.length,
      }
    );

    // Extract title and body from the JSON item
    let title = createDiscussionItem.title
      ? createDiscussionItem.title.trim()
      : "";
    let bodyLines = createDiscussionItem.body.split("\n");

    // If no title was found, use the body content as title (or a default)
    if (!title) {
      title = createDiscussionItem.body || "Agent Output";
    }

    // Apply title prefix if provided via environment variable
    const titlePrefix = process.env.GITHUB_AW_DISCUSSION_TITLE_PREFIX;
    if (titlePrefix && !title.startsWith(titlePrefix)) {
      title = titlePrefix + title;
    }

    // Add AI disclaimer with workflow run information
    const runId = context.runId;
    const runUrl = context.payload.repository
      ? `${context.payload.repository.html_url}/actions/runs/${runId}`
      : `https://github.com/actions/runs/${runId}`;
    bodyLines.push(
      ``,
      ``,
      `> Generated by Agentic Workflow Run [${runId}](${runUrl})`,
      ""
    );

    // Prepare the body content
    const body = bodyLines.join("\n").trim();

    console.log("Creating discussion with title:", title);
    console.log("Category ID:", categoryId);
    console.log("Body length:", body.length);

    try {
      // Create the discussion using GitHub REST API
      const { data: discussion } = await github.request(
        "POST /repos/{owner}/{repo}/discussions",
        {
          owner: context.repo.owner,
          repo: context.repo.repo,
          title: title,
          body: body,
          category_id: categoryId,
        }
      );

      console.log(
        "Created discussion #" + discussion.number + ": " + discussion.html_url
      );
      createdDiscussions.push(discussion);

      // Set output for the last created discussion (for backward compatibility)
      if (i === createDiscussionItems.length - 1) {
        core.setOutput("discussion_number", discussion.number);
        core.setOutput("discussion_url", discussion.html_url);
      }
    } catch (error) {
      console.error(
        `✗ Failed to create discussion "${title}":`,
        error instanceof Error ? error.message : String(error)
      );
      throw error;
    }
  }

  // Write summary for all created discussions
  if (createdDiscussions.length > 0) {
    let summaryContent = "\n\n## GitHub Discussions\n";
    for (const discussion of createdDiscussions) {
      summaryContent += `- Discussion #${discussion.number}: [${discussion.title}](${discussion.html_url})\n`;
    }
    await core.summary.addRaw(summaryContent).write();
  }

  console.log(
    `Successfully created ${createdDiscussions.length} discussion(s)`
  );
}
await main();
