// URL filtering function
function filterURLs(content, allowDomains) {
  if (!content || typeof content !== 'string') {
    return { filteredContent: '', removedURLs: [] };
  }
  
  let removedURLs = [];
  let filteredContent = content;
  
  // Default GitHub-owned domains when no domains are configured
  const defaultGitHubDomains = ['github.com', 'github.io', 'githubusercontent.com', 'githubassets.com', 'githubapp.com', 'github.dev'];
  
  // Helper function to determine if URL should be filtered
  function shouldFilterURL(rawURL) {
    try {
      const url = new URL(rawURL);
      
      // Always filter non-HTTPS URLs
      if (url.protocol !== 'https:') {
        return true;
      }
      
      // Use default GitHub domains if no domains are configured
      const domainsToCheck = (allowDomains && allowDomains.length > 0) ? allowDomains : defaultGitHubDomains;
      
      // Check if hostname matches any allowed domain pattern
      const hostname = url.hostname.toLowerCase();
      if (!hostname) {
        return true;
      }
      
      for (const allowedDomain of domainsToCheck) {
        const domain = allowedDomain.toLowerCase().trim();
        if (!domain) continue;
        
        // Exact match
        if (hostname === domain) {
          return false;
        }
        
        // Subdomain match
        if (hostname.endsWith('.' + domain)) {
          return false;
        }
      }
      
      return true;
    } catch (error) {
      // If we can't parse it, filter it out for safety
      return true;
    }
  }
  
  // Handle markdown links: [text](url)
  const markdownLinkRegex = /\[([^\]]*)\]\(([^)]+)\)/g;
  filteredContent = filteredContent.replace(markdownLinkRegex, (match, linkText, linkURL) => {
    if (shouldFilterURL(linkURL)) {
      removedURLs.push(linkURL);
      return linkText ? linkText + ' [filtered]' : '[filtered]';
    }
    return match;
  });
  
  // Handle plain URLs (including all protocols)
  const urlRegex = /[a-zA-Z][a-zA-Z0-9+.-]*:\/\/[^\s<>"'\[\]{}()]+/g;
  filteredContent = filteredContent.replace(urlRegex, (match) => {
    if (shouldFilterURL(match)) {
      removedURLs.push(match);
      return '[filtered]';
    }
    return match;
  });
  
  return { filteredContent, removedURLs };
}

async function main() {
  // Read the agent output content from environment variable
  const outputContent = process.env.GITHUB_AW_AGENT_OUTPUT;
  if (!outputContent) {
    console.log('No GITHUB_AW_AGENT_OUTPUT environment variable found');
    return;
  }

  if (outputContent.trim() === '') {
    console.log('Agent output content is empty');
    return;
  }

  console.log('Agent output content length:', outputContent.length);

  // Get allowed domains from environment variable
  const allowDomains = process.env.GH_AW_ALLOW_DOMAINS ? process.env.GH_AW_ALLOW_DOMAINS.split(',') : null;
  
  // Filter URLs in the content
  const urlFilterResult = filterURLs(outputContent, allowDomains);
  const filteredContent = urlFilterResult.filteredContent;
  if (urlFilterResult.removedURLs.length > 0) {
    console.log('Filtered URLs:', urlFilterResult.removedURLs);
  }

  // Check if we're in an issue or pull request context
  const isIssueContext = context.eventName === 'issues' || context.eventName === 'issue_comment';
  const isPRContext = context.eventName === 'pull_request' || context.eventName === 'pull_request_review' || context.eventName === 'pull_request_review_comment';

  if (!isIssueContext && !isPRContext) {
    console.log('Not running in issue or pull request context, skipping comment creation');
    return;
  }

  // Determine the issue/PR number and comment endpoint
  let issueNumber;
  let commentEndpoint;

  if (isIssueContext) {
    if (context.payload.issue) {
      issueNumber = context.payload.issue.number;
      commentEndpoint = 'issues';
    } else {
      console.log('Issue context detected but no issue found in payload');
      return;
    }
  } else if (isPRContext) {
    if (context.payload.pull_request) {
      issueNumber = context.payload.pull_request.number;
      commentEndpoint = 'issues'; // PR comments use the issues API endpoint
    } else {
      console.log('Pull request context detected but no pull request found in payload');
      return;
    }
  }

  if (!issueNumber) {
    console.log('Could not determine issue or pull request number');
    return;
  }


  let body = filteredContent.trim();
  // Add AI disclaimer with run id, run htmlurl
  const runId = context.runId;
  const runUrl = `${context.payload.repository.html_url}/actions/runs/${runId}`;  
  body += `\n\n> Generated by Agentic Workflow Run [${runId}](${runUrl})\n`;

  console.log(`Creating comment on ${commentEndpoint} #${issueNumber}`);
  console.log('Comment content length:', body.length);

  // Create the comment using GitHub API
  const { data: comment } = await github.rest.issues.createComment({
    owner: context.repo.owner,
    repo: context.repo.repo,
    issue_number: issueNumber,
    body: body
  });

  console.log('Created comment #' + comment.id + ': ' + comment.html_url);

  // Set output for other jobs to use
  core.setOutput('comment_id', comment.id);
  core.setOutput('comment_url', comment.html_url);

  // write comment id, url to the github_step_summary
  await core.summary.addRaw(`

## GitHub Comment
- Comment ID: ${comment.id}
- Comment URL: ${comment.html_url}
`).write();

}
await main();