name: Test Cleaner

on:
  schedule:
    # Run every hour at minute 0
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Close test issues and PRs
        uses: actions/github-script@v7
        with:
          script: |
            const prefix = "[Custom Engine Test]";
            
            // Close issues with the prefix
            const issues = await github.rest.issues.listForRepo({
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: 'open',
                per_page: 100
            });
            
            for (const issue of issues.data) {
            if (issue.title.startsWith(prefix) && !issue.pull_request) {
                console.log(`Closing issue: ${issue.title} (#${issue.number})`);
                await github.rest.issues.update({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: issue.number,
                    state: 'closed'
                });
            }
            }
            
            // Close pull requests with the prefix
            const pulls = await github.rest.pulls.list({
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: 'open',
                per_page: 100
            });
            
            for (const pr of pulls.data) {
            if (pr.title.startsWith(prefix)) {
                console.log(`Closing pull request: ${pr.title} (#${pr.number})`);
                await github.rest.pulls.update({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    pull_number: pr.number,
                    state: 'closed'
                });
            }
            }
